[package]
name = "csv_logger"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
serde = { version = "1.0.196", features = ["derive"] }
chrono = "0.4.34"
csv = "1.3.0"
signal-hook = "0.3.17"

driver = { path = "../lib/driver" }
